version: "3.9"

services:
  notion_tree_app:
    image: dasher1038/notion-tree:latest
    container_name: notion_tree_app
    ports:
      - "443:3000"
    entrypoint: [ "/app/fetch_env.sh" ]
    command: [ "node", "app.js" ]
    restart: always
