#배포용

version: "3.9"

services:
  notion_tree_app:
    image: dasher1038/notion-tree:latest
    container_name: notion_tree_app
    ports:
      - "80:3000"
    entrypoint: [ "/fetch_env.sh" ] #/app/fetch_env.sh가 원본임 
