#배포용 

version: "latest"

services:
  notion_tree_app:
    image: dasher1038/notion-tree:latest
    container_name: notion_tree_app
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped